### ISSUE TITLE
Entry box doesn't follow row if new row is added.

### ISSUE THREAD

**Issue by jarcane** [MattiNieminen/reabledit#2]
If a new row is added to the table while a cell has an active entry box, the entry box stays in place while the row being edited moves down.

**Comment by MattiNieminen** [comment]
This is a tricky one. The table holds the current position as a vector [row col], and if a new row comes in before the current position, the current position "changes". This does not matter if the user is not editing a cell, but upon editing the results are certainly misleading to the user.

Unfortunately, the fix is not easy. The table should somehow know that it was rendered again, and it gained new rows and must modify the current position accordingly.

**Comment by MattiNieminen** [comment]
Fixed in commit https://github.com/MattiNieminen/reabledit/commit/bb5201142b5145688e5cf5fee5c28e1df8d48fb8
